Explain function Max_Rootdepth
EcoExtreML/STEMMUS_SCOPE pull request #176
Opened 2023-05-24 14:08 UTC by EntingTang

### Description
Please add a description of the changes proposed in the pull request.

### Update executable file
Please re-generate exe file if matlab codes are changed. About how to create an exe file, see [exe readme](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/exe/README.md).

### Checklist
- [ ] Add a reference to related issues.
- [ ] @mentions of the person or team responsible for reviewing proposed changes.
- [ ] This pull request has a descriptive title.
- [ ] Code is written according to the [guidelines](http://cnl.sogang.ac.kr/cnlab/lectures/programming/matlab/Richard_Johnson-MatlabStyle2_book.pdf).
- [ ] The checks by [MISS_HIT style checker and linter](https://github.com/EcoExtreML/STEMMUS_SCOPE/blob/main/CONTRIBUTING.md#follow-matlab-style-guidelines), below the pull request, are successful (green).
- [ ] Documentation is available.
- [ ] Model runs successfully.

closes #164

2023-05-24 14:23 UTC, Yunfei-Wang1993 commented on src/Max_Rootdepth.m
> +    Elmn_Lnth = 0; %Rooting depth of each layer
comment body must be separated with whitespace from the starting %

2023-05-24 14:26 UTC, Crystal-szj requested changes
@EntingTang Thanks for your effort. Please see my comments in the code.

2023-05-24 14:26 UTC, Crystal-szj commented on src/Max_Rootdepth.m
>  %% REFERENCES
```suggestion

```

2023-05-24 14:26 UTC, Crystal-szj commented on src/Max_Rootdepth.m
> +
```suggestion
```

2023-05-24 14:26 UTC, Crystal-szj commented on src/Max_Rootdepth.m
> +        if Elmn_Lnth < Tot_Depth - R_depth %
```suggestion
        if Elmn_Lnth < Tot_Depth - R_depth

```

2024-06-14 08:45 UTC, SarahAlidoost commented
@EntingTang @Crystal-szj Hi, are you still working on this pull request? can you please fix the conflict and finalize the pull request? so it can be merged after that. If you need help with fixing the "merge conflict", let me know.

2024-06-17 10:45 UTC, Crystal-szj approved these changes

2024-06-17 14:27 UTC, Crystal-szj commented
Hi @SarahAlidoost, I've fixed the conflict and compared the results using [compare_git_branch_results.ipynb](https://github.com/Crystal-szj/STEMMUS_SCOPE/blob/main/test/compare_git_branch_results.ipynb). The results are same.

I would like to push the comparison results, but I am encountering [an issue with the passphrase](https://github.com/orgs/EcoExtreML/discussions/235) on my local computer, so I haven't been able to push the results yet.

2024-06-17 15:23 UTC, SarahAlidoost commented
> Hi @SarahAlidoost, I've fixed the conflict and compared the results using [compare_git_branch_results.ipynb](https://github.com/Crystal-szj/STEMMUS_SCOPE/blob/main/test/compare_git_branch_results.ipynb). The results are same. Thus, the changes for the `Max_Rootdepth` function are ready to merge into the `main` branch.
> 
> I'm wondering if it is beneficial to push the comparison results as well. Currently, I am encountering [an issue with the passphrase](https://github.com/orgs/EcoExtreML/discussions/235) on my local computer, so I haven't been able to push the results yet.

Thanks for fixing the pull request. no need to run the test notebook or re-generate the exe file because the changes are about adding comments only. Feel free to merge.

2024-06-17 16:11 UTC, merged